### ISSUE TITLE
Parallel fetching of artifacts

### ISSUE THREAD

**Issue by ghost** [buschmais/jqa-m2repo-plugin#5]
### Feature Description

I as a dependency graph builder 
would like to fetch artifacts from maven repository in parallel
so that fetching artifacts is faster.

### Additional information on the requested Feature
Especially for initial graph construction from big repositories (millions of artifacts) fetching can take days.

### How to Test
Number of connections 

To test this feature total opened connections to maven http server can be checked.

### Definition of Done for the Implementers
- [ ] We got a final feedback from the reporting user
- [ ] Unittests have been written
- [ ] Integration tests have been written
- [ ] Test coverage is the same or even better then before
- [ ] Documentation has been written
- [ ] Added a note on the new feature to the release notes

**Comment by obfischer** [comment]
Hi @DirkMahler, 
Could you please have a look at it. It is possible to realize this feature request?
