### ISSUE TITLE
Migrate the Plugin Documentation of the M2 Repository Plugin to the new Reference Manual

### ISSUE THREAD

**Issue by obfischer** [buschmais/jqa-m2repo-plugin#6]
### Task Description

Migrate the existing documentation of the M2 Repository Plugin to the new reference manul.

### Definition of Done for the Implementers
- [ ] The reference manual contains the same information as the old user manual
- [ ] The section on the M2 Repository Plugin in the old user manual points to the section for the plugin in the reference manual

**Comment by StephanPirnbaum** [comment]
Plugin removed from Core distribution.
